branches:
  only: master
arch:
  - arm64
  - ppc64le
  - s390x
language: node_js
node_js:
  - 10
  - 12
  - 14
  - 16
install:
  - npm install --global npm
  - npm ci --ignore-scripts
script: npm test --ignore-scripts
