branches:
  only:
  - master
arch:
  - arm64
  - ppc64le
  - s390x
os: linux
dist: bionic
language: node_js
node_js:
  - 10.24.1
  - 12.22.12
  - 14.21.3
  - 16.20.2
  - 17.9.1
install: npm ci --ignore-scripts
script: npm run-script test:ci
