branches:
  only:
  - master
arch:
  - arm64
  - ppc64le
  - s390x
os: linux
dist: bionic
language: node_js
node_js:
  - 10
  - 12
  - 14
  - 16
  - 17
install: npm ci --ignore-scripts
script: npm run-script test:ci
